name: Shell Command

on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Start node server
        run: echo "Run a node script"
      - name: Push a random file
        run: |
          pwd 
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "test@test.com"
          git config --global user.name "test"
          git fetch
          git checkout master
          git branch --set-upstream-to=origin/master
          git pull
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add -A
          git commit -m "random f"
          git push
      - name: Start Multiple Scripts
        run: |
          node -v
          npm -v
      - name: JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Yash
      - name: Log
        run: echo "${{ steps.greet.outputs.time }}"